### ISSUE TITLE
Setting the value programatically only works on initial render

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-select#25]
It appears that internally `frost-select` needs the `selected` property to be an array, although the API examples show it accepting a single integer as well. However, this only works on initial render, where  the `init()` method converts a  single integer into a single-item array:

https://github.com/ciena-frost/ember-frost-select/blob/master/addon/components/frost-select.js#L272-L277

If you try to pass in a new `selected` it breaks b/c there's no `.indexOf()` on a `Number`
https://github.com/ciena-frost/ember-frost-select/blob/master/addon/components/frost-select.js#L125

## Workaround
Pass in a single item array when using `frost-select`
```hbs
{{frost-select
  selected=[1]
}}
``

**Comment by agonza40** [comment]
This issue was fixed at the same time the "selectedValue" attribute was added.
